error fix for params and image
Next.js 15 change. In App Router, props.params is now a Promise. If access params.documentId directly will get that warning.
Fix by using useParams to avoid warning

Error: Invalid src prop
because Next.js’s <Image> component only allows images from certain domains for optimization, and files.edgestore.dev is not yet whitelisted in next.config.js.
To fix by add it to the images.remotePatterns config.